name: Tests

on:
  push:
    branches:
      - main
      - ci
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_BENCHMARKS=OFF
          cmake --build .
      - name: Tests
        run: |
          cd build
          ctest -C Debug --output-on-failure
